### ISSUE TITLE
command sign_cert: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by enthalpychange** [mathiasertl/django-ca#29]
this is a reopen for #14 

I'm getting the same error when running sign_cert, with or without specifying the `--expires` parameter. The fix mentioned for management/base.py fixes this issue.

```
python manage.py sign_cert --expires=365 --alt test.example.com
File "/home/user/.virtualenvs/sandbox/local/lib/python2.7/site-packages/django_ca/management/commands/sign_cert.py", line 118, in handle
  if ca.expires < options['expires']:
TypeError: can't compare offset-naive and offset-aware datetimes
```

Here are the values being compared. One is aware, the other is not:
```
ca.expires = 2027-10-13 00:00:00+00:00
options['expires'] = 2018-10-15 00:00:00
```

```
>>> from datetime import datetime, timedelta
>>> from django.utils import six, timezone
>>> value = 365

#original code produces timezone naive datetime
>>> now = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
>>> now + timedelta(days=value + 1)
datetime.datetime(2018, 10, 15, 0, 0)

#suggested fix produces timezone aware datetime
>>> now = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
>>> timezone.make_aware(now + timedelta(days=value + 1), timezone.get_current_timezone())
datetime.datetime(2018, 10, 15, 0, 0, tzinfo=<UTC>)```

**Comment by redNixon** [comment]
I ran into this as well, I believe that the behavior difference seen by users/devs in #14 is due to "USE_TZ" being set differently in their project's settings file.  This setting will make the model timezone aware if set to True, however "now" is always being created as timezone unaware. [See the documentation here.](https://docs.djangoproject.com/en/1.11/topics/i18n/timezones/).

As a quick test, can you flip the current value to see if that fixes your issue?  If USE_TZ is not defined in your settings.py then it is defaulting to False, so USE_TZ=True would be the opposite value.

**Comment by redNixon** [comment]
Confirmed this is being caused by USE_TZ which is set to False in the django-ca settings.py file by default(also the Django default fwiw):

> ./manage.py sign_cert --expires=365 --alt test.example.com
> --Use_TZ = False
> ipdb> print("%s  ---  %s" % (ca.expires, options['expires']))
> 2027-10-13 00:00:00  ---  2018-10-15 00:00:00
> --Use_TZ = True
> ipdb> print("%s  ---  %s" % (ca.expires, options['expires']))
> 2027-10-13 00:00:00+00:00  ---  2018-10-15 00:00:00

The webUI does not suffer from this issue because django_ca/forms.py uses converts ca.expires to a datetime.date first since that matches the data type of what the form is submitting:

_forms.py:190_   
```
if ca and expires and ca.expires.date() < expires:
    ...
```
Changing sign_cert to use the same logic as forms seems like the easiest method to fix.

**Comment by mathiasertl** [comment]
Hi,

Thanks for the report. Due to more information then in #14, I was actually able to fix the issue. This will be with the next release of django-ca.

@enthalpychange If you do not wait that long, temporarily applying #30 should also fix the issue for you.

@redNixon Thanks for the pull request as well. I was not quite happy with the fix, because it addressed the symptom and not the cause. I hope you like the commited fix as well!
